### ISSUE TITLE
appear twice error

### ISSUE THREAD

**Issue by zdx3578** [tambetm/gymexperiments#4]
with mujoco: when run a long time, programe is crack.

1
For comparison, real replay memory contains 21739 experiences
WARNING: Nan, Inf or huge value in QACC at DOF 0. The simulation is unstable. Time = 0.1200.

Performing imagination rollout for 5 steps
Traceback (most recent call last):
  File "naf_ir.py", line 255, in <module>
    postobs, rewards, terminals = ir_model.predict(preobs, actions, timesteps + i)
  File "/home/ubuntu/work/gymexperiments/irmodel.py", line 105, in predict
    obsmeans = obsmodel.predict(X)[0]
  File "/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/base.py", line 200, in predict
    return self._decision_function(X)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/base.py", line 183, in _decision_function
    X = check_array(X, accept_sparse=['csr', 'csc', 'coo'])
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 398, in check_array
    _assert_all_finite(array)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 54, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

2
Done fitting, 200 timesteps covered.
Performing imagination rollout for 5 steps
Done, fictional replay memory now contains 100000 experiences
For comparison, real replay memory contains 21001 experiences
WARNING: Nan, Inf or huge value in QACC at DOF 0. The simulation is unstable. Time = 0.0900.

Performing imagination rollout for 5 steps
Traceback (most recent call last):
  File "naf_ir.py", line 255, in <module>
    postobs, rewards, terminals = ir_model.predict(preobs, actions, timesteps + i)
  File "/home/ubuntu/work/gymexperiments/irmodel.py", line 105, in predict
    obsmeans = obsmodel.predict(X)[0]
  File "/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/base.py", line 200, in predict
    return self._decision_function(X)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/base.py", line 183, in _decision_function
    X = check_array(X, accept_sparse=['csr', 'csc', 'coo'])
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 398, in check_array
    _assert_all_finite(array)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 54, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by tambetm** [comment]
naf_ir.py is not rigorously tested, I never got it fully working. Feel free to send pull request!
